LIBRETRO_COMM_DIR := $(CORE_DIR)/libretro-common
INCFLAGS := -I$(LIBRETRO_COMM_DIR)/include

SOURCES_ASM := 

SOURCES_CXX := $(CORE_DIR)/bg_manager.cpp \
	$(CORE_DIR)/game.cpp \
	$(CORE_DIR)/game_manager.cpp \
	$(CORE_DIR)/libretro.cpp \
	$(CORE_DIR)/sfx_manager.cpp \

SOURCES_C :=

SOURCES_C += $(CORE_DIR)/rpng_front.c
SOURCES_C += $(CORE_DIR)/blit_surface_data.c
SOURCES_C += $(CORE_DIR)/blit_attr_table.c
SOURCES_C += $(CORE_DIR)/blit_alt_table.c
SOURCES_C += $(CORE_DIR)/blit_surface.c
SOURCES_C += $(CORE_DIR)/blit_render_target.c
SOURCES_C += $(CORE_DIR)/blit_surface_cluster.c
SOURCES_C += $(CORE_DIR)/blit_str_map.c
SOURCES_C += $(CORE_DIR)/blit_tile_set.c
SOURCES_C += $(CORE_DIR)/blit_xml.c
SOURCES_C += $(CORE_DIR)/blit_surface_cache.c
SOURCES_C += $(CORE_DIR)/blit_font.c
SOURCES_C += $(CORE_DIR)/blit_tilemap.c
SOURCES_C += $(CORE_DIR)/audio/mixer_f32.c
SOURCES_C += $(CORE_DIR)/audio/mixer_i16.c
SOURCES_C += $(CORE_DIR)/audio/vorbis_f32.c
SOURCES_C += $(CORE_DIR)/audio/vorbis_i16.c
SOURCES_C += $(CORE_DIR)/audio/async_job.c

ifeq ($(STATIC_LINKING), 1)
else
SOURCES_C += \
				 $(LIBRETRO_COMM_DIR)/audio/audio_mix.c \
				 $(LIBRETRO_COMM_DIR)/audio/conversion/float_to_s16.c \
				 $(LIBRETRO_COMM_DIR)/audio/conversion/s16_to_float.c \
				 $(LIBRETRO_COMM_DIR)/compat/compat_posix_string.c \
				 $(LIBRETRO_COMM_DIR)/compat/compat_strl.c \
				 $(LIBRETRO_COMM_DIR)/compat/fopen_utf8.c \
				 $(LIBRETRO_COMM_DIR)/encodings/encoding_crc32.c \
				 $(LIBRETRO_COMM_DIR)/encodings/encoding_deflate.c \
				 $(LIBRETRO_COMM_DIR)/encodings/encoding_utf.c \
				 $(LIBRETRO_COMM_DIR)/features/features_cpu.c \
				 $(LIBRETRO_COMM_DIR)/file/file_path.c \
				 $(LIBRETRO_COMM_DIR)/file/file_path_io.c \
				 $(LIBRETRO_COMM_DIR)/formats/data_transfer.c \
				 $(LIBRETRO_COMM_DIR)/formats/audio_transfer.c \
				 $(LIBRETRO_COMM_DIR)/formats/image_transfer.c \
				 $(LIBRETRO_COMM_DIR)/formats/vorbis/rvorbis.c \
				 $(LIBRETRO_COMM_DIR)/formats/wav/rwav.c \
				 $(LIBRETRO_COMM_DIR)/formats/xml/rxml.c \
				 $(LIBRETRO_COMM_DIR)/formats/png/rpng.c \
				 $(LIBRETRO_COMM_DIR)/formats/png/rpng_apng.c \
				 $(LIBRETRO_COMM_DIR)/memmap/memmap.c \
				 $(LIBRETRO_COMM_DIR)/rthreads/rthreads.c \
				 $(LIBRETRO_COMM_DIR)/streams/file_stream.c \
				 $(LIBRETRO_COMM_DIR)/streams/trans_stream.c \
				 $(LIBRETRO_COMM_DIR)/streams/trans_stream_deflate.c \
				 $(LIBRETRO_COMM_DIR)/streams/trans_stream_pipe.c \
				 $(LIBRETRO_COMM_DIR)/string/rstrtod.c \
				 $(LIBRETRO_COMM_DIR)/string/stdstring.c \
				 $(LIBRETRO_COMM_DIR)/time/rtime.c \
				 $(LIBRETRO_COMM_DIR)/vfs/vfs_implementation.c

ifeq ($(HAVE_NEON),1)
	SOURCES_ASM += $(LIBRETRO_COMM_DIR)/audio/conversion/float_to_s16_neon.S \
						$(LIBRETRO_COMM_DIR)/audio/conversion/s16_to_float_neon.S
endif
endif
